apiVersion: v1
kind: Namespace
metadata:
  name: qwen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-awq-vllm
  namespace: qwen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-vllm
  template:
    metadata:
      labels:
        app: qwen3-vllm
    spec:
      nodeSelector:
        accelerator: nvidia-gpu
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: vllm
          image: vllm/vllm-openai:latest
          args:
            - --model
            - Qwen/Qwen3-4B-AWQ
            - --served-model-name
            - qwen3
            - --quantization
            - awq
            - --max-model-len
            - "32768"
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: "14Gi"
            requests:
              nvidia.com/gpu: 1
              memory: "14Gi"
          volumeMounts:
            - name: hf-cache
              mountPath: /root/.cache/huggingface
      volumes:
        - name: hf-cache
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-awq-svc
  namespace: qwen
spec:
  type: LoadBalancer
  selector:
    app: qwen3-vllm
  ports:
    - port: 8000
      targetPort: 8000