apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: qwen3-cluster
  region: ap-northeast-1
  version: "1.32"

vpc:
  nat:
    gateway: Single    # NAT付き

managedNodeGroups:
  - name: gpu-ng
    instanceType: g4dn.xlarge
    desiredCapacity: 1
    amiFamily: AmazonLinux2
    publicNetworking: true
    labels:
      accelerator: nvidia
    taints:
      - key: nvidia.com/gpu
        value: "true"
        effect: NoSchedule

  - name: cpu-ng
    instanceType: t3.medium
    desiredCapacity: 1
    amiFamily: AmazonLinux2