apiVersion: v1
kind: Namespace
metadata:
  name: qwen4b-custom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen3-4b-custom-vllm
  namespace: qwen4b-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen3-4b-custom-vllm
  template:
    metadata:
      labels:
        app: qwen3-4b-custom-vllm
    spec:
      nodeSelector:
        accelerator: nvidia # Selects the existing g4dn.xlarge node
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      volumes:
        - name: model-storage
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
      initContainers:
        - name: model-downloader
          image: alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache unzip wget;
              echo "Downloading model from S3...";
              wget -O /model_repo/awq_model.zip https://kanazawa-qwen.s3.ap-northeast-1.amazonaws.com/awq_model.zip;
              echo "Unzipping model...";
              unzip /model_repo/awq_model.zip -d /model_repo/model_files;
              echo "Init container finished.";
          volumeMounts:
            - name: model-storage
              mountPath: /model_repo
      containers:
        - name: vllm
          image: vllm/vllm-openai:latest
          args:
            - --model
            - /model_repo/model_files # Path to the unzipped model
            - --served-model-name
            - qwen3-4b-custom
            - --quantization
            - awq
            - --max-model-len
            - "32768"
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: "14Gi"
            requests:
              nvidia.com/gpu: 1
              memory: "14Gi"
          volumeMounts:
            - name: model-storage
              mountPath: /model_repo
            - name: dshm
              mountPath: /dev/shm
---
apiVersion: v1
kind: Service
metadata:
  name: qwen3-4b-custom-svc
  namespace: qwen4b-custom
spec:
  type: LoadBalancer
  selector:
    app: qwen3-4b-custom-vllm
  ports:
    - port: 8000
      targetPort: 8000
